[package]
name = "apns-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
jsonwebtoken = { version = "9.3.0", features = ["use_pem"] }
serde = "1.0.203"
toml = "0.8.14"
env_logger = "0.11.3"
isahc = "1.7.2"
serde_json = "1.0.117"

